### ISSUE TITLE
Deleting a file exception

### ISSUE THREAD

**Issue by sherif181** [HoloSound/AIC14W_G06_T02#8]
I have  noticed the folowing exception while deleting a file   may be i was clicking toofast 

] (http--0.0.0.0-8080-3) listFiles(): returning 5 datasets.
13:49:38,802 INFO  [Raid1] (http--0.0.0.0-8080-3) Deleting hex_inv_255.bin from DropBox.
13:49:40,951 INFO  [Raid1] (http--0.0.0.0-8080-3) File hex_inv_255.bin deleted from DropBox.
13:49:40,951 INFO  [Raid1] (http--0.0.0.0-8080-3) Deleting hex_inv_255.bin from BOX.
13:49:45,560 INFO  [Raid1] (http--0.0.0.0-8080-3) File hex_inv_255.bin deleted from BOX.
13:49:45,561 INFO  [Raid1] (http--0.0.0.0-8080-3) Deleting hex_inv_255.bin from AS3.
13:49:47,432 INFO  [Raid1] (http--0.0.0.0-8080-3) File hex_inv_255.bin deleted from AS3.
13:49:47,438 INFO  [Raid1] (http--0.0.0.0-8080-3) Deleting hex_inv_255.bin from DropBox.
13:49:49,704 INFO  [Raid1] (http--0.0.0.0-8080-6) listFiles(): 
13:49:49,704 INFO  [Raid1] (http--0.0.0.0-8080-6)   Querying files from DropBox.
13:49:50,366 ERROR [stderr] (http--0.0.0.0-8080-3) com.dropbox.core.DbxException$BadResponseCode: unexpected HTTP status code: 404: {"error": "Path '/hex_inv_255.bin' not found"}
13:49:50,367 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:212)
13:49:50,367 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxClient$18.handle(DbxClient.java:1894)
13:49:50,368 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxClient$18.handle(DbxClient.java:1889)
13:49:50,368 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxRequestUtil.finishResponse(DbxRequestUtil.java:279)
13:49:50,368 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxRequestUtil.doPostNoAuth(DbxRequestUtil.java:272)
13:49:50,369 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxRequestUtil.doPost(DbxRequestUtil.java:262)
13:49:50,369 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxClient.doPost(DbxClient.java:1952)
13:49:50,369 ERROR [stderr] (http--0.0.0.0-8080-3) 	at com.dropbox.core.DbxClient.delete(DbxClient.java:1889)
13:49:50,370 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.connector.DropBoxImpl.delete(DropBoxImpl.java:339)
13:49:50,370 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.Raid1.delete(Raid1.java:308)
13:49:50,370 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.sessionbean.Raid1SessionBean.delete(Raid1SessionBean.java:34)
13:49:50,371 ERROR [stderr] (http--0.0.0.0-8080-3) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:49:50,371 ERROR [stderr] (http--0.0.0.0-8080-3) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
13:49:50,371 ERROR [stderr] (http--0.0.0.0-8080-3) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:49:50,372 ERROR [stderr] (http--0.0.0.0-8080-3) 	at java.lang.reflect.Method.invoke(Method.java:622)
13:49:50,372 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptorFactory$ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptorFactory.java:72)
13:49:50,372 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,373 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
13:49:50,373 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:36)
13:49:50,373 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,374 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
13:49:50,374 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,375 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
13:49:50,375 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,375 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
13:49:50,376 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)
13:49:50,376 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,376 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
13:49:50,377 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,377 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:228)
13:49:50,377 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:304)
13:49:50,378 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:190)
13:49:50,378 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,378 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
13:49:50,379 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,379 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
13:49:50,379 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,380 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
13:49:50,380 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,380 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:32)
13:49:50,380 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,380 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
13:49:50,381 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,381 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
13:49:50,381 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165)
13:49:50,381 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:173)
13:49:50,382 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
13:49:50,382 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
13:49:50,382 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:72)
13:49:50,382 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.sessionbean.RaidSessionBeanInterface$$$view2.delete(Unknown Source)
13:49:50,382 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.web.Raid1Servlet.deleteFile(Raid1Servlet.java:496)
13:49:50,383 ERROR [stderr] (http--0.0.0.0-8080-3) 	at at.tuwien.aic.raid.web.Raid1Servlet.doGet(Raid1Servlet.java:120)
13:49:50,383 ERROR [stderr] (http--0.0.0.0-8080-3) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
13:49:50,383 ERROR [stderr] (http--0.0.0.0-8080-3) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
13:49:50,383 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
13:49:50,383 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
13:49:50,384 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
13:49:50,385 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
13:49:50,385 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
13:49:50,385 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
13:49:50,385 ERROR [stderr] (http--0.0.0.0-8080-3) 	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
13:49:50,385 ERROR [stderr] (http--0.0.0.0-8080-3) 	at java.lang.Thread.run(Thread.java:701)
13:49:50,386 INFO  [Raid1] (http--0.0.0.0-8080-3) File hex_inv_255.bin deleted from DropBox.

**Comment by HoloSound** [comment]
The main problem was that the file does not exist.
Maybe we can something do with the Exceptions - that they were not shown.

**Comment by HoloSound** [comment]
Deleting a file that does not exist @ DropBox - shows the stack trace in logging.
I think that problem have we analysed - and found no real solution.
Using FileNotFoundException (sub if IOException) - but the handling has some problems?
